import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import { RevealLinks } from "@/components/RevealLink";

const geistSans = localFont({
  src: "./fonts/Montreal Medium.otf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
      <body
        className={`${geistSans.variable} container bg-[#C5C5C5] antialiased px-4`}
      >
        <div className="navbar-container">
          <Navbar />
        </div>
        {children}
        <RevealLinks />
      </body>
      </Provider>
    </html>
  );
}

