import React from 'react';
import Navbar from '@/components/Navbar';
import Provider from '@/components/Provider';
import PreloaderWrapper from '@/components/PreLoaderWrapper';
import LocalTime from '@/components/LocalTime';
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/Montreal Medium.otf",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${geistSans.variable} bg-[#E3E3DE] antialiased mx-auto`}>
          <PreloaderWrapper>
            <div className="navbar-container">
              <Navbar />
            </div>
            <main>{children}</main>
          </PreloaderWrapper>
        </body>
      </Provider>
    </html>
  );
}
